INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('1', 'Berenice', 'Miettinen', 'bmiettinen0@marketwatch.com', '1', 'inactive', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('2', 'Irwinn', 'Hinsch', 'ihinsch1@businesswire.com', '2', 'inactive', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('3', 'Penni', 'Seyffert', 'pseyffert2@sfgate.com', '5', 'pending', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('4', 'Jackie', 'Miroy', 'jmiroy3@cbc.ca', '1', 'inactive', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('5', 'Morgun', 'Leborgne', 'mleborgne4@twitpic.com', '1', 'active', 'Human Resources');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('6', 'Englebert', 'Lapley', 'elapley5@deviantart.com', '1', 'active', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('7', 'Marie-jeanne', 'Lorey', 'mlorey6@virginia.edu', '3', 'pending', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('8', 'Aggy', 'Ripsher', 'aripsher7@jigsy.com', '4', 'pending', 'Human Resources');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('9', 'Odelia', 'Arkley', 'oarkley8@state.gov', '5', 'pending', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('10', 'Faustina', 'Surgood', 'fsurgood9@google.com.br', '3', 'inactive', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('11', 'Hatti', 'Lunam', 'hlunama@jalbum.net', '3', 'pending', 'Human Resources');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('12', 'Delcine', 'Castiglione', 'dcastiglioneb@jugem.jp', '1', 'inactive', 'Engineering');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('13', 'Harland', 'Pithcock', 'hpithcockc@quantcast.com', '4', 'inactive', 'Engineering');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('14', 'Fowler', 'De Goey', 'fdegoeyd@google.com', '4', 'pending', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('15', 'Elwin', 'Prendeville', 'eprendevillee@linkedin.com', '4', 'pending', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('16', 'Leon', 'Carlill', 'lcarlillf@tuttocitta.it', '4', 'pending', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('17', 'Veronika', 'Wike', 'vwikeg@g.co', '4', 'pending', 'Human Resources');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('18', 'Sallee', 'Woolacott', 'swoolacotth@xing.com', '5', 'active', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('19', 'Loni', 'O''Grady', 'logradyi@nsw.gov.au', '3', 'inactive', 'Engineering');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('20', 'Rycca', 'Ferreira', 'rferreiraj@amazonaws.com', '2', 'pending', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('21', 'Zonda', 'Antyukhin', 'zantyukhink@marketwatch.com', '5', 'inactive', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('22', 'Gothart', 'Bruneton', 'gbrunetonl@moonfruit.com', '4', 'pending', 'Human Resources');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('23', 'Nikolaus', 'Lowen', 'nlowenm@blog.com', '4', 'pending', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('24', 'Gail', 'Yukhnin', 'gyukhninn@slideshare.net', '4', 'inactive', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('25', 'Morey', 'Enrdigo', 'menrdigoo@163.com', '4', 'pending', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('26', 'Marie', 'Nicholes', 'mnicholesp@so-net.ne.jp', '3', 'inactive', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('27', 'Brooks', 'Bruna', 'bbrunaq@sogou.com', '3', 'pending', 'Engineering');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('28', 'Shirlene', 'Georgievski', 'sgeorgievskir@blog.com', '3', 'inactive', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('29', 'Alysia', 'Srutton', 'asruttons@imageshack.us', '3', 'pending', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('30', 'Ginelle', 'Conti', 'gcontit@over-blog.com', '4', 'active', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('31', 'Sidnee', 'Malone', 'smaloneu@edublogs.org', '4', 'pending', 'Human Resources');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('32', 'Alanson', 'Szymanski', 'aszymanskiv@oracle.com', '3', 'inactive', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('33', 'Sharai', 'Howden', 'showdenw@vimeo.com', '2', 'inactive', 'Engineering');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('34', 'Terrel', 'De Angelo', 'tdeangelox@ed.gov', '1', 'pending', 'Marketing');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('35', 'Damiano', 'Antonsen', 'dantonseny@live.com', '2', 'pending', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('36', 'Kerwinn', 'Roistone', 'kroistonez@wikia.com', '3', 'active', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('37', 'Amabelle', 'Carling', 'acarling10@csmonitor.com', '1', 'pending', 'Human Resources');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('38', 'Carena', 'Pinnell', 'cpinnell11@unicef.org', '2', 'pending', 'Finance');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('39', 'Daryn', 'Espadate', 'despadate12@army.mil', '3', 'inactive', 'Sales');
INSERT INTO SystemAdmin (adminID, firstName, lastName, email, adminLvl, acctStatus, dept) VALUES ('40', 'Verena', 'Featherstonhaugh', 'vfeatherstonhaugh13@elegantthemes.com', '3', 'pending', 'Finance');
