INSERT INTO Schools (schoolID, name, city, state) VALUES ('1', 'Sycamore Ridge Middle', 'Asikkala', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('2', 'Cedar Grove High', 'Sędziejowice', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('3', 'Hillcrest Elementary', 'Maguwon', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('4', 'Sunnydale Elementary', 'Duogongma', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('5', 'Sunnydale Elementary', 'Gedongmulyo', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('6', 'Riverdale Prep', 'Ambatondrazaka', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('7', 'Sycamore Ridge Middle', 'Seattle', 'Washington');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('8', 'Hillcrest Elementary', 'Pidsandawan', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('9', 'Maplewood High School', 'Abū Mūsā', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('10', 'Sunnydale Elementary', 'Port Glaud', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('11', 'Crestwood Elementary', 'Otyniya', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('12', 'Cedar Grove High', 'San Francisco', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('13', 'Cedar Grove High', 'Otofuke', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('14', 'Riverside High', 'Stockholm', 'Stockholm');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('15', 'Pine Grove Middle', 'Eshowe', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('16', 'Hillcrest Elementary', 'Penghu', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('17', 'Harbor Point Middle School', 'Sydney', 'New South Wales');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('18', 'Meadowview Academy', 'Fucun', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('19', 'Riverside High', 'Diancun', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('20', 'Riverdale Prep', 'Valašská Polanka', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('21', 'Sycamore Ridge Middle', 'Preserje pri Radomljah', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('22', 'Greenwood Academy', 'Jobabo', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('23', 'Golden Hills Academy', 'Hanam', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('24', 'Riverside High', 'Pokachi', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('25', 'Hillcrest Elementary', 'Ранковце', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('26', 'Crestwood Elementary', 'Jicun', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('27', 'Sunrise Elementary', 'Lingcheng', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('28', 'Willow Creek Academy', 'Guadalupe', 'Puebla');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('29', 'Sunset Hills Elementary', 'Santa Maria', 'Yucatan');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('30', 'Willowbrook Middle School', 'Los Angeles', 'California');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('31', 'Brookside High', 'Carvalhinho', 'Setúbal');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('32', 'Springfield Academy', 'Dan Khun Thot', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('33', 'Mountain View Elementary', 'San Jose', 'California');
INSERT INTO Schools (schoolID, name, city, state) VALUES ('34', 'Golden Hills Academy', 'La Fortuna', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('35', 'Oak Ridge Elementary', 'Lipnica', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('36', 'Crestwood Elementary', 'Xijiang', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('37', 'Sunnydale Elementary', 'San Simon', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('38', 'Harbor Point Middle School', 'Huaribamba', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('39', 'Hilltop Elementary', 'Nueve de Julio', NULL);
INSERT INTO Schools (schoolID, name, city, state) VALUES ('40', 'Sunnydale Elementary', 'Denton', 'Texas');
