INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('1', 'PURE SHEER', 'Castillos', 'VGPY', 'EuroLeague');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('2', 'Lipitor', 'Nogent-le-Rotrou', 'eaMy', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('3', 'Candida Plus', 'Daba', 'qetA', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('4', 'AVAPRO', 'Igede-Ekiti', 'CzyJh', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('5', 'Stool Softener', 'Toumodi', 'OARZS', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('6', 'DawnMist Deodorant Bar No. 1 1/2', 'Namp’o', 'ZjVyzr', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('7', 'Rainbow Baby', 'Sinargalih', 'fNkxX', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('8', 'Risperidone', 'Baleagung', 'nqeL', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('9', 'Loratadine', 'Yuntan', 'dhQy', 'EuroLeague');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('10', 'The First Ampoule Essence BB', 'La Plaine-Saint-Denis', 'tsvc', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('11', 'freshnails', 'Legok', 'QEuk', 'NBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('12', 'Ceftriaxone Sodium', 'Dushanbe', 'KAji', 'AAU');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('13', 'Mycogone perniciosa', 'Lago da Pedra', 'QissCu', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('14', 'Theraproxen-90', 'Mira', 'TUGeUY', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('15', 'Citalopram', 'Chapayeve', 'DGjX', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('16', 'Ibuprofen', 'Labansari', 'hcMsX', 'EuroLeague');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('17', 'Exchange Select Lansoprazole', 'Paseyan', 'AOgo', 'NBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('18', 'Sulfamethoxazole and Trimethoprim', 'Qalaikhumb', 'xSIY', 'NBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('19', 'Zonegran', 'San Antonio Ilotenango', 'RyNU', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('20', 'Nasal Decongestant PE', 'Depok', 'dNwb', 'NBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('21', 'AugmentinXR', 'Tabwakea Village', 'zoPtr', 'EuroLeague');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('22', 'EcoCare 250', 'Huicungo', 'RkVr', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('23', 'Teflaro', 'Fryčovice', 'xJWrB', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('24', 'Latanoprost', 'Krasni Okny', 'oPzjjQ', 'AAU');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('25', 'rexall night time cold and flu', 'Jagupit', 'DcjAQ', 'AAU');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('26', 'Losartan Potassium', 'Tualangcut', 'CLvB', 'AAU');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('27', 'Lemon Zest Antibacterial Foaming Hand Wash', 'Punākha', 'KRUs', 'EuroLeague');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('28', 'Omeprazole', 'Kyrylivka', 'BToJs', 'NBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('29', 'Lymph I', 'Sandia', 'mqtoUF', 'NBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('30', 'PEMF Optimizer', 'Wufeng', 'gzQb', 'NBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('31', 'Antacid', 'Smedjebacken', 'JcFV', 'AAU');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('32', 'Ibuprofen', 'Hepu', 'LYjwR', 'EuroLeague');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('33', 'Penicillin V Potassium', 'El Cafetal', 'vNRvx', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('34', 'Ciprodex', 'Gunungkendeng', 'rDECQk', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('35', 'Verapamil', 'Malawag', 'TDtF', 'EuroLeague');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('36', 'Clopidogrel bisulfate', 'Jetafe', 'KwabQA', 'High School');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('37', 'Azithromycin Dihydrate', 'Parral', 'FfxI', 'AAU');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('38', 'Plexus coeliacus 6 Special Order', 'Hope', 'ccowi', 'WNBA');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('39', 'Leader Anti-Itch', 'Bronnitsy', 'IFYsr', 'AAU');
INSERT INTO Teams (teamID, teamName, city, teamAbbrev, league) VALUES ('40', 'Testosterone Enanthate', 'Ōfunato', 'bACS', 'AAU');
