INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('1', 'Botsford and Sons', '11', '7/11/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('2', 'Miller and Sons', '23', '4/8/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('3', 'Hilll, Von and Smitham', '14', '9/16/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('4', 'Simonis-Koelpin', '6', '5/28/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('5', 'Ritchie-Smith', '10', '2/17/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('6', 'Will and Sons', '31', '4/7/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('7', 'Nader-Kshlerin', '12', '8/9/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('8', 'Hyatt, Terry and Boyer', '29', '8/4/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('9', 'Hartmann, Marquardt and Padberg', '25', '7/19/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('10', 'Carroll Group', '22', '3/15/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('11', 'Gibson, Lesch and Fisher', '25', '11/16/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('12', 'Wiza Inc', '30', '9/6/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('13', 'Grant-Lakin', '5', '9/26/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('14', 'Zulauf, Paucek and Hand', '4', '6/27/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('15', 'Batz, Pfannerstill and Beatty', '11', '4/21/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('16', 'Pfannerstill and Sons', '25', '12/28/2024');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('17', 'Leuschke, Thompson and Greenholt', '25', '6/12/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('18', 'Grant Inc', '13', '6/24/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('19', 'Gleichner-Hahn', '30', '10/16/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('20', 'Hoppe-Konopelski', '12', '10/17/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('21', 'Gusikowski LLC', '38', '5/1/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('22', 'Heaney LLC', '27', '5/28/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('23', 'Quigley, Bailey and Cartwright', '31', '11/10/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('24', 'Senger-Dooley', '17', '7/9/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('25', 'Hagenes and Sons', '17', '4/16/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('26', 'Thiel Group', '37', '9/11/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('27', 'Erdman and Sons', '35', '4/14/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('28', 'Torp and Sons', '28', '3/21/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('29', 'Hammes-Zemlak', '2', '10/6/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('30', 'Gerlach-Gerhold', '11', '6/27/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('31', 'Herzog, Koelpin and Moen', '38', '5/11/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('32', 'Conroy, Rogahn and Stamm', '19', '5/4/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('33', 'Jenkins-Batz', '28', '9/21/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('34', 'Grant, Grimes and McKenzie', '24', '1/3/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('35', 'Swift, Schuster and Wunsch', '35', '10/20/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('36', 'Smitham Inc', '23', '1/13/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('37', 'Grady and Sons', '11', '10/12/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('38', 'Von and Sons', '26', '6/13/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('39', 'Bradtke, Kub and Tremblay', '20', '1/7/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('40', 'Nienow Inc', '22', '10/2/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('41', 'Schaden-Upton', '9', '3/13/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('42', 'Witting-Wiegand', '15', '9/19/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('43', 'Gerlach Group', '10', '4/13/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('44', 'Denesik Inc', '1', '10/9/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('45', 'Kling LLC', '12', '5/6/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('46', 'Rohan, Hansen and Fay', '18', '1/27/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('47', 'Hettinger LLC', '28', '11/8/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('48', 'Rogahn, Beatty and Jacobs', '22', '8/9/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('49', 'Emmerich Inc', '14', '7/14/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('50', 'Konopelski, Bednar and Keebler', '26', '5/21/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('51', 'Kuhlman-Collins', '34', '12/25/2024');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('52', 'Parisian Inc', '13', '9/29/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('53', 'Purdy Group', '12', '8/13/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('54', 'Baumbach-Volkman', '34', '8/20/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('55', 'Moen-Cartwright', '12', '2/6/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('56', 'Nicolas and Sons', '17', '9/10/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('57', 'Johnson-Bernhard', '14', '5/15/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('58', 'Kuhlman, Durgan and Smitham', '8', '2/9/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('59', 'Hoeger Inc', '22', '7/30/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('60', 'Ritchie LLC', '38', '9/25/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('61', 'Kessler, Schmitt and Raynor', '8', '5/4/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('62', 'McCullough and Sons', '24', '1/27/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('63', 'Lubowitz and Sons', '20', '12/14/2024');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('64', 'Hoppe and Sons', '31', '5/13/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('65', 'Deckow, Wiegand and Jenkins', '12', '5/16/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('66', 'Shanahan, Schmidt and Wisoky', '18', '9/13/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('67', 'Welch LLC', '2', '7/19/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('68', 'Gorczany-Glover', '3', '12/2/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('69', 'Bins LLC', '4', '1/1/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('70', 'Simonis and Sons', '16', '6/10/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('71', 'Bosco, Jones and Smith', '32', '9/6/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('72', 'White and Sons', '27', '6/16/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('73', 'Pouros Inc', '39', '6/8/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('74', 'Emard Inc', '10', '7/8/2025');
INSERT INTO CalculatedMetrics (metricID, formulaName, gameID, calcTimeStamp) VALUES ('75', 'Jacobson Group', '14', '9/17/2025');
